<?php
/**
 * Created by PhpStorm.
 * Author: Konstantin Kaluzhnikov k.kaluzhnikov@gmail.com
 * Date: 22.08.2017
 */

return array(
    'site_name' => 'MySite',
    'version'   => 'versiya',

    'REST' => [
        'Dashboard' => [
            'page' => [ 'title' =>'Dashboard',],
        ],
        'Users' => [
            'page' => [ 'title' =>'Müştərilər',],
            'fields'    => [
                'login'         => 'Giriş',
                'groupName'     => 'Grup adı',
                'industryName'  => 'Sənayə adı',
                'name'          => 'Müştərinin аdı',
                'description'   => 'Təsvir',
                'createdAt'     => 'Yaradılma tarixi',
                'status'        => 'Status',
            ],
        ],
        'Industries' => [
            'page' => [ 'title' =>'Sənayə',],
            'fields'    => [
                'title'         => 'Ad',
            ],
        ],
        'PostTypes' => [
            'page' => [ 'title' =>'Tiplər',],
            'fields'    => [
                'title'         => 'Ad',
            ],
        ],
        'Posts' => [
            'page' => [ 'title' =>'Posts',],
            'fields'    => [
                'name'          => 'Müştərinin аdı',
                'createdAt'     => 'Yaradılma tarixi',
                'title'         => 'Başlıq',
                'text'          => 'Mətn',
                'status'        => 'Status',
            ],
        ],
        'Pages' => [
            'page' => [ 'title' =>'Səhifələr',],
            'fields'    => [
                'alias'         => 'Ləqəb',
                'title'         => 'Başlıq',
            ],
        ],
        'Banners' => [
            'page' => [ 'title' =>'Banners',],
            'fields'    => [
                'name'          => 'Client`s name',
                'type'          => 'Type',
                'title'         => 'Title',
                'start'         => 'Start',
                'stop'          => 'Stop',
            ],
        ],
        'BannersClients' => [
            'page' => [ 'title' =>'Banner`s clients',],
            'fields'    => [
                'name'         => 'Name',
            ],
        ],
    ],

    'New item added'                                            => 'Yeni element əlavə edildi',
    'New item not added'                                        => 'Yeni element əlavə edilmədi',
    'Item %item_id% not found'                                  => '%item_id% elementi tapılmadı',
    'Item %item_id% updated'                                    => '%item_id% elementi yeniləndi',
    'Item %item_id% not updated'                                => '%item_id% elementi yenilənmədi',
    'You have no access'                                        => 'Giriş mövcud deyil',
    'File deleted'                                              => 'Fayl silindi',
    'File was not deleted'                                      => 'Fayl silinmədi',
    'User does not exists'                                      => 'İstifadəçi tapəlmadı',
    'Wrong login or password'                                   => 'Login vəya parol səhvdir',
    'Please, check email to complete registration'              => 'Qeydiyyatınızın tamamlanması üçün emailinizi yoxlayın',
    'An error occurred. Please contact administrator'           => 'Xəta əmələ gəldi. Administratornan əlaqə saxlayın',
    'Wrong activation code.'                                    => 'Yanlış aktivasiya kodu.',
    'Conformation complete. Please, sign in.'                   => 'Təsdiq olundu. Xahiş edirik,hesabınıza daxil olun.',
    'Please, check email'                                       => 'Elektron poçtunuzu yoxlayın ',
    'Wrong login or email'                                      => 'Yanlış login vəya elektron poçt ünvanı',
    'Email was send'                                            => 'Məktub göndərildı',
    'Record not found'                                          => 'Qeyd tapılmadı',
    'Record not deleted'                                        => 'Qeyd silindi',
    'Records not deleted'                                       => 'Qeydlər silinmədi',
    'At least one record not found!'                            => 'Ən az bir qeyd tapılmadı',
    'Profile updated'                                           => 'Profil yeniləndi',
    'Profile not updated'                                       => 'Profil yenilənmədi',
    'Invalid value'                                             => 'Yanlış dəyər',
    'Select an industry'                                        => 'Sənayə seçin',
    'Select a contact'                                          => 'Əlaqə seçin',
    'Select a group'                                            => 'Grup seçin',
    'Select a city'                                             => 'Şəhər seçin',
    'Invalid email'                                             => 'Səhv elektron poçt ünvanı',
    'Invalid url'                                               => 'Səhv url',
    'Append contact'                                            => 'Əlaqə məlumatlarını əlavə et',
    'Minimum of 6 characters'                                   => 'Ən az 6 simvol',
    'Password don\'t match'                                     => 'Parol uyğun gəlmir',
    'Please enter your login and email to repair your password' => 'Parolu bərpa etmək üçün login və elektron poçt ünvanınısı daxil edin',
    'Please sign in'                                            => 'Xahiş edirik daxil olun',
    'I forgot my password'                                      => 'Parolu unutdum',
    'By register yourself at %link% you will get'               => ' %link%də qeyd olaraq, əldə edəcəksiniz',
    'Access to the services'                                    => 'Xidmətlərə giriş',
    'Your new password is'                                      => 'Sizin yeni parolunuz',
    'Best regards'                                              => 'Hörmətlə',
    'Thank you for registration on %link%'                      => '%link% də qeydiyyatdan keçdiyinizə görə təşəkkür edirik',
    'To complete registration, click on the link below'         => 'Qeydiyyatın tamamlanması üçün aşağıdaki linkdən keçid alın',
    'Page not found'                                            => 'Səhifə tapılmadı',
    'Method must be one of'                                     => 'Metod bunlardandan biri olmalıdır',
    'Write a massage'                                           => 'Mesaj yaz',
    'Download attachment'                                       => 'Əlavə fayl yüklə',
    'Are you sure?'                                             => 'Əminsinizmi?',
    'Type Message ...'                                          => 'Mesaj yazın ...',
    'You have %msgs% new messages'                              => 'Sizn %msgs% yeni mesajınız var',
    'See All Messages'                                          => 'Bütün mesajlara bax',
    'Add new item'                                              => 'Yeni element əlavə et',
    'Delete items'                                              => 'Elementləri sil',
    'No result found!'                                          => 'Nəticə tapılmadı!',
    'Record could not be deleted'                               => 'Qeyd silinə bilməz',
    'At least one record could not be deleted'                  => 'Ən az bir qeyd silinə bilməz',
    'Payment amount per month'                                  => 'Bir aylıq ödəniş məbləği',
    'Select amount of months you want to pay for'               => 'Ödəmək istədiyiniz ayların sayılarını seçin',
    'Total amount to be paid'                                   => 'Ödəniləcək yekun məbləğ',
    "Login '%login%' already exists."                           => "Login '%login%' artıq mövcud deyil.",
    "Email '%email%' already exists."                           => "Elektron poçt '%email%' artıq mövcud deyil.",
    "You must first agree to the terms"                         => "Şərtləri qəbul etməlisiniz.",
    "I understand, accept, and agree to the following %terms%." => "Mən %terms% başa düşdüm və razıyam.",
    "terms and conditions"                                      => "şərtləri",

    'Actions'                   => 'Əməliyyatlar',
	'MENU'						=> 'MENÜ',
    'Approved'                  => 'Təsdiqləndi',
    'On moderation'             => 'Moderasiyada',
    'Finished'                  => 'Tamamlandı',
    'New'                       => 'Yeni',
    'Edit'                      => 'Redaktə etmək',
    'Delete'                    => 'Silmək',
    'Industry'                  => 'Sənaye',
    'Description'               => 'Təsvir',
    'Created AT'                => 'Yaradılma tarixi',
    'Suppliers'                 => 'Təchizatçılar',
	'Buyers'					=> 'Alıcılar',
    'Status'                    => 'Status',
    'Messages'                  => 'Mesajlar',
    'Conformation'              => 'Təsdiq',
    'Info'                      => 'Məlumat',
    'Error!'                    => 'Səhv!',
    'Contact'                   => 'Əlaqə',
    'Contacts'                  => 'Əlaqələr',
    'Profile'                   => 'Profil',
    'Mailbox'                   => 'Poçt qutusu',
    'Billing options'           => 'Ödəniş seçənəkləri',
    'Referals'                  => 'Referallar',
    'Help'                      => 'Kömək',
    'Support'                   => 'Dəstək',
    'Submit'                    => 'Göndərmək',
    'Cancel'                    => 'Ləğv etmək',
    'Title'                     => 'Başlıq',
    'Text'                      => 'Mətn',
    'Name'                      => 'Ad Soyad',
    'Alias'                     => 'Ləqəb',
    'Keywords'                  => 'Açar sözlər',
    'Short description'         => 'Qısa təsvir',
    'Full description'          => 'Tam təsvir',
    'Attachment'                => 'Əlavə',
    'Moderate'                  => 'Moderasiyadan keçirmək',
    'Download'                  => 'Endirmək',
    'All records'               => 'Bütün qeydlər',
    'Group'                     => 'Grup',
    'City'                      => 'Şəhər',
    'Address'                   => 'Ünvan',
    'Phone'                     => 'Telefon',
    'Site'                      => 'Sayt (nümunə: http://example.com)',
	'Facebook'					=> 'Facebook (nümunə: https://www.facebook.com/example/)',	
    'Position'                  => 'Vəzifə',
    'Login'                     => 'Login',
    'Password'                  => 'Parol',
    'New password'              => 'Yeni parol',
    'Confirm password'          => 'Parolu təsdiqlə',
    'Forgot password'           => 'Parolunuzu unutmusunuz',
    'Sign in'                   => 'GİRİŞ',
    'Sign out'                  => 'Çıxış',
    'Sign up'                   => 'QEYDİYYATDAN KEÇ',
    'Why?'                      => 'NİYƏ?',
    'Remember me'               => 'Məni yadda saxla',
    'Registration'              => 'Qeydiyyat',
    'Buyer'                     => 'Alıcı',
    'Supplier'                  => 'Təchizatçı',
    'Company'                   => 'Şirkət',
	'Country'					=> 'Ölkə',
    'From'                      => '	-dən',
    'Hello'                     => 'Salam',
    'Create'                    => 'Yarad',
    'Update'                    => 'Yenilə',
    'Participate'               => 'İştirak et',
    'Back'                      => 'Geri',
    'Send'                      => 'Göndər',
    'New supplier'              => 'Yeni təchizatçılar',
    'ADMINISTRATIVE TOOLS'      => 'ADMİNİSTAROTOR MENYUSU',
    'Settings'                  => 'Ayarlar',
    'Home'                      => 'ANA SƏHİFƏ',
    'Blog'                      => 'Blog',
    'About'                     => 'Haqqımızda',
    'Contact info'              => 'Əlaqə məlumatı',
    'Finish'                    => 'Sonlandır',
    'Question'                  => 'Sual',
    'Answer'                    => 'Cavab',
    'Months'                    => 'Aylar',
    'Pay'                       => 'Ödəniş edin',
    'Services'                  => 'XİDMƏTLƏR',
    'Partners'                  => 'Tərəfdaşlarımız',
	'All rights reserved'		=> 'Bütün hüquqlar qorunur.',
	'Partial copying'			=> 'Materialların tam və ya qismən köçürülməsi qadağandır, platformadan materialların razılaşdırılmış şəkildə istifadəsi zamanı istinad etmək lazımdır.',

    'All News'                  => 'All News',
);