<?php
/**
 * Created by PhpStorm.
 * Author: Konstantin Kaluzhnikov k.kaluzhnikov@gmail.com
 * Date: 22.08.2017
 */

return array(
    'site_name' => 'MySite',
    'version'   => 'version',

    'REST' => [
        'Dashboard' => [
            'page' => [ 'title' =>'Dashboard',],
        ],
        'Users' => [
            'page' => [ 'title' =>'Clients',],
            'fields'    => [
                'login'         => 'Login',
                'groupName'     => 'Group',
                'industryName'  => 'Industry',
                'name'          => 'Name',
                'description'   => 'Description',
                'createdAt'     => 'Created at',
                'status'        => 'Status',
            ],
        ],
        'Industries' => [
            'page' => [ 'title' =>'Industries',],
            'fields'    => [
                'title'         => 'Title',
            ],
        ],
        'PostTypes' => [
            'page' => [ 'title' =>'Types',],
            'fields'    => [
                'title'         => 'Title',
            ],
        ],
        'Posts' => [
            'page' => [ 'title' =>'Posts',],
            'fields'    => [
                'name'          => 'Name',
                'createdAt'     => 'Created at',
                'title'         => 'Title',
                'text'          => 'Text',
                'status'        => 'Status',
            ],
        ],
        'Pages' => [
            'page' => [ 'title' =>'Pages',],
            'fields'    => [
                'alias'         => 'Alias',
                'title'         => 'Title',
            ],
        ],
    ],

    'New item added'                                            => 'New item added',
    'New item not added'                                        => 'New item not added',
    'Item %item_id% not found'                                  => 'Item %item_id% not found',
    'Item %item_id% updated'                                    => 'Item %item_id% updated',
    'Item %item_id% not updated'                                => 'Item %item_id% not updated',
    'Tender created'                                            => 'Tender created',
    'Tender was not created'                                    => 'Tender was not created',
    'Tender do not exist'                                       => 'Tender do not exist',
    'You have no access'                                        => 'You have no access',
    'Tender %item_id% not found'                                => 'Tender %item_id% not found',
    'Tender updated'                                            => 'Tender updated',
    'Tender was not updated'                                    => 'Tender was not updated',
    'File deleted'                                              => 'File deleted',
    'File was not deleted'                                      => 'File was not deleted',
    'User does not exists'                                      => 'User does not exists',
    'Wrong login or password'                                   => 'Wrong login or password',
    'Please, check email to complete registration'              => 'Please, check email to complete registration',
    'An error occurred. Please contact administrator'           => 'An error occurred. Please contact administrator',
    'Wrong activation code.'                                    => 'Wrong activation code.',
    'Conformation complete. Please, sign in.'                   => 'Conformation complete. Please, sign in.',
    'Please, check email'                                       => 'Please, check email',
    'Wrong login or email'                                      => 'Wrong login or email',
    'Email was send'                                            => 'Email was send',
    'Record not found'                                          => 'Record not found',
    'Record not deleted'                                        => 'Record not deleted',
    'Records not deleted'                                       => 'Records not deleted',
    'At least one record not found!'                            => 'At least one record not found!',
    'Profile updated'                                           => 'Profile updated',
    'Profile not updated'                                       => 'Profile not updated',
    'Invalid value'                                             => 'Invalid value',
    'Select an industry'                                        => 'Select an industry',
    'Select a contact'                                          => 'Select a contact',
    'You do not have tenders'                                   => 'You do not have tenders',
    'Select a group'                                            => 'Select a group',
    'Select a city'                                             => 'Select a city',
    'Invalid email'                                             => 'Invalid email',
    'Invalid url'                                               => 'Invalid url',
    'Append contact'                                            => 'Append contact',
    'Minimum of 6 characters'                                   => 'Minimum of 6 characters',
    'Password don\'t match'                                     => 'Password don\'t match',
    'Please enter your login and email to repair your password' => 'Please enter your login and email to repair your password',
    'Please sign in'                                            => 'Please sign in',
    'I forgot my password'                                      => 'I forgot my password',
    'By register yourself at %link% you will get'               => 'By register yourself at %link% you will get',
    'Access to the services'                                    => 'Access to the services',
    'Your new password is'                                      => 'Your new password is',
    'Best regards'                                              => 'Best regards',
    'Thank you for registration on %link%'                      => 'Thank you for registration on %link%',
    'To complete registration, click on the link below'         => 'To complete registration, click on the link below',
    'Page not found'                                            => 'Page not found',
    'Method must be one of'                                     => 'Method must be one of',
    'Write a massage'                                           => 'Write a message',
    'Download attachment'                                       => 'Download attachment',
    'Are you sure?'                                             => 'Are you sure?',
    'Type Message ...'                                          => 'Type Message ...',
    'Add new tender'                                            => 'Add new tender',
    'There are no tenders at the moment.'                       => 'There are no tenders at the moment.',
    'You have no suppliers for the tender!'                     => 'You have no suppliers for the tender!',
    'You have %msgs% new messages'                              => 'You have %msgs% new messages',
    'See All Messages'                                          => 'See All Messages',
    'Add new item'                                              => 'Add new item',
    'Delete items'                                              => 'Delete items',
    'No result found!'                                          => 'No result found!',
    'Record could not be deleted'                               => 'Record could not be deleted',
    'At least one record could not be deleted'                  => 'At least one record could not be deleted',
    'Are you sure, you want to finish tender?'                  => 'Are you sure, you want to finish tender?',
    'Payment amount per month'                                  => 'Payment amount per month',
    'Select amount of months you want to pay for'               => 'Select amount of months you want to pay for',
    'Total amount to be paid'                                   => 'Total amount to be paid',
    "Login '%login%' already exists."                           => "Login '%login%' already exists.",
    "Email '%email%' already exists."                           => "Email '%email%' already exists.",
    "You must first agree to the terms"                         => "You must first agree to the terms.",
    "I understand, accept, and agree to the following %terms%." => "I understand, accept, and agree to the following %terms%.",
    "terms and conditions"                                      => "terms and conditions",
    'Cost of new tender: %money% AZN'       		            => 'Cost of new tender: %money% AZN',
    'The cost of participation in a tender: %money% AZN'        => 'The cost of participation in a tender: %money% AZN',
    'promo action'                                              => ' (Promotion)',
    'Buy access to this tender'                                 => 'Buy access to this tender',
    'You must apply resume to participate the tender'           => 'You must apply resume to participate the tender',

    'Actions'                   => 'Actions',
	'MENU'						=> 'MENU',
    'Approved'                  => 'Approved',
    'On moderation'             => 'On moderation',
    'Finished'                  => 'Finished',
    'New'                       => 'New',
    'Edit'                      => 'Edit',
    'Delete'                    => 'Delete',
    'Industry'                  => 'Industry',
    'Tender'                    => 'Tender',
    'Tenders'                   => 'Tenders',
    'Description'               => 'Description',
    'Created AT'                => 'Created at',
    'Suppliers'                 => 'Suppliers',
	'Buyers'					=> 'Buyers',
    'Status'                    => 'Status',
    'Messages'                  => 'Messages',
    'Conformation'              => 'Conformation',
    'Info'                      => 'Info',
    'Error!'                    => 'Error!',
    'Contact'                   => 'Contacts',
    'Contacts'                  => 'Contacts',
    'Profile'                   => 'Profile',
    'Mailbox'                   => 'Mailbox',
    'Billing options'           => 'Billing options',
    'Referals'                  => 'Referals',
    'Help'                      => 'Help',
    'Support'                   => 'Support',
    'Submit'                    => 'Submit',
    'Cancel'                    => 'Cancel',
    'Title'                     => 'Title',
    'Text'                      => 'Text',
    'Name'                      => "Name Surname",
    'Alias'                     => 'Alias',
    'Keywords'                  => 'Keywords',
    'Short description'         => 'Short description',
    'Full description'          => 'Full description',
    'Attachment'                => 'Attachment(*pdf,*docs,*txt,*xlsx)',
    'Moderate'                  => 'Moderate',
    'Download'                  => 'Download',
    'All records'               => 'All records',
    'Group'                     => 'Group',
    'City'                      => 'City',
    'Address'                   => 'Address',
    'Phone'                     => 'Phone',
    'Site'                      => 'Site (example: http://example.com)',
	'Facebook'					=> 'Facebook (example: https://www.facebook.com/example/)',
    'Position'                  => 'Position',
    'Login'                     => 'Login',
    'Password'                  => 'Password',
    'New password'              => 'New password',
    'Confirm password'          => 'Confirm password',
    'Forgot password'           => 'Forgot password',
    'Sign in'                   => 'Sign in',
    'Sign out'                  => 'Sign out',
    'Sign up'                   => 'Sign up',
    'Why?'                      => 'Why?',
    'Remember me'               => 'Remember me',
    'Registration'              => 'Registration',
    'Buyer'                     => 'Buyer',
    'Supplier'                  => 'Supplier',
    'Company'                   => 'Company',
	'voen'						=> 'Tax ID',
	'Country'					=> 'Country',
    'From'                      => 'From',
    'Hello'                     => 'Hello',
    'Create'                    => 'Create',
	'Tender Name'               => 'Tender Name',
	'Tender Name'               => 'Tender Name',
    'Update'                    => 'Update',
    'Participate'               => 'Participate',
    'Back'                      => 'Back',
    'Send'                      => 'Send',
    'My tenders'                => 'My tenders',
    'Active tenders'            => 'Active tenders',
    'New tenders'               => 'New tenders',
    'New supplier'              => 'New supplier',
    'ADMINISTRATIVE TOOLS'      => 'ADMINISTRATIVE TOOLS',
    'Settings'                  => 'Settings',
    'Home'                      => 'Home',
    'Blog'                      => 'Blog',
    'About'                     => 'About',
    'Contact info'              => 'Contact info',
    'Finish'                    => 'Finish',
    'Question'                  => 'Question',
    'Answer'                    => 'Answer',
    'Months'                    => 'Months',
    'Pay'                       => 'Pay',
    'Services'                  => 'Services',
    'Partners'                  => 'Partners',
    'Tender ends at'            => 'Tender ends at',
	'All rights reserved'		=> 'All rights reserved.',
	'Partial copying'			=> 'Full or partial copying of materials is prohibited, with consistent use of materials from the platform, refer to the resource.',
);