<?php
/**
 * Created by PhpStorm.
 * Author: Konstantin Kaluzhnikov k.kaluzhnikov@gmail.com
 * Date: 22.08.2017
 */

return array(
    'site_name' => 'MySite',
    'version'   => 'версия',

    'REST' => [
        'Dashboard' => [
            'page' => [ 'title' =>'Dashboard',],
        ],
        'Users' => [
            'page' => [ 'title' =>'Пользователи',],
            'fields'    => [
                'login'         => 'Логин',
                'groupName'     => 'Группа',
                'industryName'  => 'Индустрия',
                'name'          => 'Имя',
                'description'   => 'Описание',
                'createdAt'     => 'Дата создания',
                'status'        => 'Статус',
            ],
        ],
        'Industries' => [
            'page' => [ 'title' =>'Индустрии',],
            'fields'    => [
                'title'         => 'Название',
            ],
        ],
        'PostTypes' => [
            'page' => [ 'title' =>'Типы',],
            'fields'    => [
                'title'         => 'Название',
            ],
        ],
        'Posts' => [
            'page' => [ 'title' =>'Posts',],
            'fields'    => [
                'name'          => 'Имя',
                'createdAt'     => 'Дата создания',
                'title'         => 'Заголовок',
                'text'          => 'Текст',
                'status'        => 'Статус',
            ],
        ],
        'Pages' => [
            'page' => [ 'title' =>'Страницы',],
            'fields'    => [
                'alias'         => 'Alias',
                'title'         => 'Заголовок',
            ],
        ],
    ],

    'New item added'                                            => 'Новый элемент добавлен',
    'New item not added'                                        => 'Новый элемент не был добавлен',
    'Item %item_id% not found'                                  => 'Элемент %item_id% не найден',
    'Item %item_id% updated'                                    => 'Элемент %item_id% обновлен',
    'Item %item_id% not updated'                                => 'Элемент %item_id% не обновлен',
    'Tender created'                                            => 'Тендер создан',
    'Tender was not created'                                    => 'Тендер не обновлен',
    'Tender do not exist'                                       => 'Тендер не существует',
    'You have no access'                                        => 'У вас нет доступа',
    'Tender %item_id% not found'                                => 'Тендер %item_id% не найден',
    'Tender updated'                                            => 'Тендер обновлен',
    'Tender was not updated'                                    => 'Тендер не обновлен',
    'File deleted'                                              => 'Файл удален',
    'File was not deleted'                                      => 'Файл не удален',
    'User does not exists'                                      => 'Пользователь не найден',
    'Wrong login or password'                                   => 'Неправильный логин или пароль',
    'Please, check email to complete registration'              => 'Пожалуйста, проверьте email для завершения регистрации',
    'An error occurred. Please contact administrator'           => 'Произошла ошибка. Пожалуйста, свяжитесь с администратором',
    'Wrong activation code.'                                    => 'Неправильный код активации.',
    'Conformation complete. Please, sign in.'                   => 'Подтверждение завершено. Пожалуйста, войдите в свой аккаунт.',
    'Please, check email'                                       => 'Пожалуйста, проверьте email',
    'Wrong login or email'                                      => 'Неправильный логин или email',
    'Email was send'                                            => 'Письмо отправлено',
    'Record not found'                                          => 'Запись не найдена',
    'Record not deleted'                                        => 'Запись не удалена',
    'Records not deleted'                                       => 'Записи не удалены',
    'At least one record not found!'                            => 'Как минимум одна запись не найдена',
    'Profile updated'                                           => 'Профиль обновлен',
    'Profile not updated'                                       => 'Профиль не обновлен',
    'Invalid value'                                             => 'Неверное значение',
    'Select an industry'                                        => 'Выберите индустрию',
    'Select a contact'                                          => 'Выберите контакт',
    'You do not have tenders'                                   => 'У вас нет тендеров',
    'Select a group'                                            => 'Выберите группу',
    'Select a city'                                             => 'Выберите город',
    'Invalid email'                                             => 'Неверный email',
    'Invalid url'                                               => 'Неверный url',
    'Append contact'                                            => 'Добавить контакт',
    'Minimum of 6 characters'                                   => 'Как минимум 6 символов',
    'Password don\'t match'                                     => 'Пароль не совпадает',
    'Please enter your login and email to repair your password' => 'Пожалуйста, введите свой логин и email для востановления пароля',
    'Please sign in'                                            => 'Пожалуйста, залогинитесь',
    'I forgot my password'                                      => 'Я забыл свой пароль',
    'By register yourself at %link% you will get'               => 'Зарегистрировавшись на %link% вы получите',
    'Access to the services'                                    => 'Доступ к услугам',
    'Your new password is'                                      => 'Ваш новый пароль',
    'Best regards'                                              => 'С уважением',
    'Thank you for registration on %link%'                      => 'Спасибо за регистрацию на %link%',
    'To complete registration, click on the link below'         => 'Для завершения регистрации нажмите на ссылку внизу',
    'Page not found'                                            => 'Страница не найдена',
    'Method must be one of'                                     => 'Метод должен быть одним из',
    'Write a massage'                                           => 'Написать сообщение',
    'Download attachment'                                       => 'Загрузить вложение',
    'Are you sure?'                                             => 'Вы уверены?',
    'Type Message ...'                                          => 'Напишите сообщение ...',
    'Add new tender'                                            => 'Добавить тендер',
    'There are no tenders at the moment.'                       => 'Сейчас нет ни одного тендера.',
    'You have no suppliers for the tender!'                     => 'У вас нет поставщиков для этого тендера!',
    'You have %msgs% new messages'                              => 'У вас %msgs% новых сообщений',
    'See All Messages'                                          => 'Просмотреть все сообщения',
    'Add new item'                                              => 'Добавить новый элемент',
    'Delete items'                                              => 'Удалить элементы',
    'No result found!'                                          => 'Результат не найден!',
    'Record could not be deleted'                               => 'Запись не может быть удалена',
    'At least one record could not be deleted'                  => 'Как минимум одна запись не может быть удалена',
    'Are you sure, you want to finish tender?'                  => 'Вы уверены, что хотите завершить этот тендер?',
    'Payment amount per month'                                  => 'Стоимость одного месяца',
    'Select amount of months you want to pay for'               => 'Выберите количество месяцев, которые вы хотите оплатить',
    'Total amount to be paid'                                   => 'Сумма к оплате',
    "Login '%login%' already exists."                           => "Логин '%login%' уже существует.",
    "Email '%email%' already exists."                           => "Email '%email%' уже существует.",
    "You must first agree to the terms"                         => "Вы должны согласиться с условиями.",
    "I understand, accept, and agree to the following %terms%." => "Я понимаю и согласен со следующими %terms%.",
    "terms and conditions"                                      => "политикой и правилами",
    'Cost of new tender: %money% AZN'                           => 'Стоимость размещения тендера: %money% AZN',
    'The cost of participation in a tender: %money% AZN'        => 'Стоимость участия в тендере: %money% AZN',
    'promo action'                                              => ' (Действует промоакция)',
    'Buy access to this tender'                                 => 'Преобрести доступ для участия',
    'You must apply resume to participate the tender'           => 'Внесите необходимую информацию для участия в тендере',

    'Actions'                   => 'Действия',
	'MENU'						=> 'МЕНЮ',
    'Approved'                  => 'Подтверждено',
    'On moderation'             => 'На модерации',
    'Finished'                  => 'Завершено',
    'New'                       => 'Новый',
    'Edit'                      => 'Редактировать',
    'Delete'                    => 'Удалить',
    'Industry'                  => 'Индустрия',
    'Tender'                    => 'Тендер',
    'Tenders'                   => 'Тендеры',
    'Description'               => 'Описание',
    'Created AT'                => 'Дата создания',
    'Suppliers'                 => 'Поставщики',
	'Buyers'					=> 'Покупатели',
    'Status'                    => 'Статус',
    'Messages'                  => 'Сообщения',
    'Conformation'              => 'Подтверждение',
    'Info'                      => 'Информация',
    'Error!'                    => 'Ошибка!',
    'Contact'                   => 'Контакты',
    'Contacts'                  => 'Контакты',
    'Profile'                   => 'Профиль',
    'Mailbox'                   => 'Почта',
    'Billing options'           => 'Опции оплаты',
    'Referals'                  => 'Рефералы',
    'Help'                      => 'Помощь',
    'Support'                   => 'Поддержка',
    'Submit'                    => 'Отправить',
    'Cancel'                    => 'Отмена',
    'Title'                     => 'Заголовок',
    'Text'                      => 'Текст',
    'Name'                      => 'Имя Фамилия',
    'Alias'                     => 'Alias',
    'Keywords'                  => 'Keywords',
    'Short description'         => 'Краткое описание',
    'Full description'          => 'Полное описание',
    'Attachment'                => 'Приложение(*pdf,*docs,*txt,*xlsx)',
    'Moderate'                  => 'Модерировать',
    'Download'                  => 'Скачать',
    'All records'               => 'Все записи',
    'Group'                     => 'Группа',
    'City'                      => 'Город',
    'Address'                   => 'Адрес',
    'Phone'                     => 'Телефон',
    'Site'                      => 'Сайт (Пример: http://example.com)',
	'Facebook'					=> 'Facebook (Пример: https://www.facebook.com/example/)',
    'Position'                  => 'Должность',
    'Login'                     => 'Логин',
    'Password'                  => 'Пароль',
    'New password'              => 'Новый пароль',
    'Confirm password'          => 'Подтвердить пароль',
    'Forgot password'           => 'Забыли пароль',
    'Sign in'                   => 'Войти',
    'Sign out'                  => 'Выйти',
    'Sign up'                   => 'Зарегистрироваться',
    'Why?'                      => 'Почему?',
    'Remember me'               => 'Запомнить меня',
    'Registration'              => 'Регистрация',
    'Buyer'                     => 'Покупатель',
    'Supplier'                  => 'Поставщик',
    'Company'                   => 'Компания',
	'Country'					=> 'Страна',
    'From'                      => 'От',
    'Hello'                     => 'Здравтсвуйте',
    'Create'                    => 'Создать',
	'Tender Name'               => 'Название тендера',
    'Update'                    => 'Обновить',
    'Participate'               => 'Принять участие',
    'Back'                      => 'Назад',
    'Send'                      => 'Послать',
    'My tenders'                => 'Мои тендеры',
    'Active tenders'            => 'Активные тендеры',
    'New tenders'               => 'Новые тендеры',
    'New supplier'              => 'Новый поставщик',
    'ADMINISTRATIVE TOOLS'      => 'МЕНЮ АДМИНИСТРАТОРА',
    'Settings'                  => 'Настройки',
    'Home'                      => 'Главная',
    'Blog'                      => 'Блог',
    'About'                     => 'О нас',
    'Contact info'              => 'Информация о контакте',
    'Finish'                    => 'Завершить',
    'Question'                  => 'Вопрос',
    'Answer'                    => 'Ответ',
    'Months'                    => 'Месяцы',
    'Pay'                       => 'Оплатить',
    'Services'                  => 'Услуги',
    'Partners'                  => 'Партнеры',
    'Tender ends at'            => 'Время завершения тендера',
	'All rights reserved'		=> 'Все права защищены.',
	'Partial copying'			=> 'Полное или частичное копирование материалов запрещено, при согласованном использовании материалов из платформы необходима ссылка на ресурс.',
);